#修改默认端口号和访问的上下文路径
server:
  port: 8090
# 配置MySQL数据源
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/excel?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid连接池
    type: com.alibaba.druid.pool.DruidDataSource
    # 配置druid连接池
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    filters: stat
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    sql-script-encoding: utf-8
---
# jpa相关配置
spring:
  jpa:
    # 更新数据表结构
    hibernate:
      ddl-auto: update
    # 在日志中打印出执行sql语句的信息
    show-sql: true
    properties:
      hibernate:
        jdbc:
          batch_size: 1000
          batch_versioned_data: true
        order_inserts: true
        order_updates: true
excel:
  table:
    head: 名称,年龄,地址,手机号,身高,性别,创建时间